# Generated by Django 2.2.7 on 2019-11-22 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('rated', models.CharField(blank=True, max_length=5, null=True)),
                ('released', models.CharField(blank=True, max_length=20, null=True)),
                ('runtime', models.CharField(blank=True, max_length=10, null=True)),
                ('genre', models.CharField(blank=True, max_length=200, null=True)),
                ('director', models.CharField(blank=True, max_length=100, null=True)),
                ('writer', models.TextField(blank=True, null=True)),
                ('actors', models.TextField(blank=True, null=True)),
                ('plot', models.TextField(blank=True, null=True)),
                ('language', models.CharField(blank=True, max_length=50, null=True)),
                ('country', models.TextField(blank=True, null=True)),
                ('awards', models.TextField(blank=True, null=True)),
                ('poster', models.CharField(blank=True, max_length=300, null=True)),
                ('metascore', models.CharField(blank=True, max_length=50, null=True)),
                ('imdb_rating', models.CharField(blank=True, max_length=10, null=True)),
                ('imdb_votes', models.CharField(blank=True, max_length=10, null=True)),
                ('imdb_id', models.CharField(blank=True, max_length=15, null=True)),
                ('type', models.CharField(blank=True, max_length=10, null=True)),
                ('dvd', models.CharField(blank=True, max_length=20, null=True)),
                ('box_office', models.CharField(blank=True, max_length=100, null=True)),
                ('production', models.CharField(blank=True, max_length=200, null=True)),
                ('website', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=10)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='movie.Movie')),
            ],
        ),
    ]
